# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:    
      - test2
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      packagejson: ${{ steps.changes.outputs.packagejson }}
      all: ${{ steps.changes.outputs.all }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERNAME }}
          password: ${{ secrets.DOCKERPWD }}
          
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=packagejson::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep package.json$ | xargs)"

      - name: Build and push
        if: github.ref == 'refs/heads/test2'
        run: |
          docker build -t xiaohongczh/test1:${GITHUB_REF##*/} -f ./Dockfile .
          docker push xiaohongczh/test1:${GITHUB_REF##*/}
   
  after-build: 
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Branch name afterbuild
        run: echo running on branch ${GITHUB_REF##*/}
  
      - name: print build echo
        run: echo ${{needs.build.outputs.packagejson}} ${{needs.build.outputs.all}}
          
      
